{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge.gradle",
    "module": "ForgeGradle",
    "version": "5.1.73",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-5.1.73.jar",
          "url": "ForgeGradle-5.1.73.jar",
          "size": 467421,
          "sha512": "44cbe4948177519c9ff4c88a4f7c6f9d8e3409d1fae7c5728a4df31f845db15a16fec87f44a54c3f39ad44ed5407bfb3db318ba0b3ba7fa1e8190d26aaac42b5",
          "sha256": "7b193425f4a3e54ea5afd70943617aba8659dc791fd2a0b8e0d5b2d990559284",
          "sha1": "6c4ec6e5fe656715f1f1ad8b021cc4318da2adf1",
          "md5": "4ccf2c7010c3ca215bfa5714f744626c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.14"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.15"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.17"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-5.1.73.jar",
          "url": "ForgeGradle-5.1.73.jar",
          "size": 467421,
          "sha512": "44cbe4948177519c9ff4c88a4f7c6f9d8e3409d1fae7c5728a4df31f845db15a16fec87f44a54c3f39ad44ed5407bfb3db318ba0b3ba7fa1e8190d26aaac42b5",
          "sha256": "7b193425f4a3e54ea5afd70943617aba8659dc791fd2a0b8e0d5b2d990559284",
          "sha1": "6c4ec6e5fe656715f1f1ad8b021cc4318da2adf1",
          "md5": "4ccf2c7010c3ca215bfa5714f744626c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeGradle-5.1.73-sources.jar",
          "url": "ForgeGradle-5.1.73-sources.jar",
          "size": 203961,
          "sha512": "79d04119cd7f51e9db5aeccf1ec9062346726c467e19a0db11d54de721169b803f6851d6fb8a9108fbc4511a435aba80131e20c630d6dc407ea98e34bec5fc35",
          "sha256": "3b38b27c4556051c5f28e6d2d63e3ac3fa13cdd1c6aa82626b5d1d8cc55b8c99",
          "sha1": "ceea13706d6983af6d1dba24331dfbd5dee4fa60",
          "md5": "5c17595fed577b0d812dcb1b73bccc30"
        }
      ]
    }
  ]
}
